from datetime import datetime, timezone
from enum import StrEnum

from sqlalchemy import JSON, BigInteger, DateTime, Enum, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from .database import Base


class MatchState(StrEnum):
    WAITING = "WAITING"
    MATCHMAKING = "MATCHMAKING"
    PROVISIONING = "PROVISIONING"
    RUNNING = "RUNNING"
    FINISHING = "FINISHING"
    FINISHED = "FINISHED"
    FAILED = "FAILED"


class Team(StrEnum):
    RED = "RED"
    BLUE = "BLUE"


class Player(Base):
    __tablename__ = "players"
    id: Mapped[int] = mapped_column(primary_key=True)
    nickname: Mapped[str] = mapped_column(String)
    token_hash: Mapped[str | None] = mapped_column(String(64), unique=True, index=True)
    active_nickname: Mapped[str | None] = mapped_column(String, unique=True, index=True)
    session_expires_at: Mapped[datetime | None] = mapped_column(DateTime)
    queued_at: Mapped[datetime | None] = mapped_column(DateTime)


class Case(Base):
    __tablename__ = "cases"
    id: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str]


class Match(Base):
    __tablename__ = "matches"
    id: Mapped[int] = mapped_column(primary_key=True)
    state: Mapped[MatchState] = mapped_column(
        Enum(MatchState, create_constraint=True), default=MatchState.WAITING,
        server_default="WAITING",
    )
    case_id: Mapped[str | None] = mapped_column(ForeignKey("cases.id"))
    seed: Mapped[int | None] = mapped_column(BigInteger)
    target_host: Mapped[str | None]
    blue_password: Mapped[str | None]
    red_key: Mapped[str | None]
    blue_key: Mapped[str | None]
    securing_started_at: Mapped[datetime | None] = mapped_column(DateTime)
    blue_key_issued_at: Mapped[datetime | None] = mapped_column(DateTime)
    arena_run_id: Mapped[str | None]
    arena_instance_id: Mapped[str | None]
    arena_cursor: Mapped[int] = mapped_column(default=0, server_default="0")
    arena_endpoints: Mapped[list | None] = mapped_column(JSON)
    arena_cleanup_pending: Mapped[bool] = mapped_column(default=False, server_default="0")


class MatchPlayer(Base):
    __tablename__ = "match_players"
    match_id: Mapped[int] = mapped_column(ForeignKey("matches.id"), primary_key=True)
    player_id: Mapped[int] = mapped_column(ForeignKey("players.id"), primary_key=True)
    team: Mapped[Team | None] = mapped_column(Enum(Team, create_constraint=True))


class MatchEvent(Base):
    __tablename__ = "match_events"
    id: Mapped[int] = mapped_column(primary_key=True)
    match_id: Mapped[int] = mapped_column(ForeignKey("matches.id"), index=True)
    type: Mapped[str]
    # SQLite stores naive UTC; timestamps are generated by the server.
    timestamp: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc).replace(tzinfo=None),
    )
    event_metadata: Mapped[dict] = mapped_column("metadata", JSON, default=dict)
